# SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
# FROM REST_INFO r
# GROUP BY r.FOOD_TYPE
# HAVING max(r.FAVORITES)
# ORDER BY r.FOOD_TYPE DESC


SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FAVORITES) in 
       (SELECT MAX(FAVORITES)
       FROM REST_INFO
       GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC

